// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'  show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9O7sxXxDaVYA9V9RYm41d2xxmhrGFlNY',
    appId: '1:180809705959:web:212b3ad70559d6b3a47542',
    messagingSenderId: '180809705959',
    projectId: 'myapp-24278',
    authDomain: 'myapp-24278.firebaseapp.com',
    storageBucket: 'myapp-24278.appspot.com',
    measurementId: 'G-TYYSXCWJRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBArlOAd8alJE9kHsef1lAHjROiutgR8',
    appId: '1:180809705959:android:f5f011ad386e8cfaa47542',
    messagingSenderId: '180809705959',
    projectId: 'myapp-24278',
    storageBucket: 'myapp-24278.appspot.com',
  );

  static const  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1u2gD1sh3gIjXwgV-aXja-cRpM4QmCto',
    appId: '1:180809705959:ios:b50b69a93bb1c9aaa47542',
    messagingSenderId: '180809705959',
    projectId: 'myapp-24278',
    storageBucket: 'myapp-24278.appspot.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1u2gD1sh3gIjXwgV-aXja-cRpM4QmCto',
    appId: '1:180809705959:ios:b50b69a93bb1c9aaa47542',
    messagingSenderId: '180809705959',
    projectId: 'myapp-24278',
    storageBucket: 'myapp-24278.appspot.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9O7sxXxDaVYA9V9RYm41d2xxmhrGFlNY',
    appId: '1:180809705959:web:6df2854050d6d326a47542',
    messagingSenderId: '180809705959',
    projectId: 'myapp-24278',
    authDomain: 'myapp-24278.firebaseapp.com',
    storageBucket: 'myapp-24278.appspot.com',
    measurementId: 'G-F14HCM5F0H',
  );
}
